### ISSUE TITLE
skill 1241000 unextractable

### ISSUE THREAD

**Issue by Jancy-49** [KENNYSOFT/WzComparerR2#128] opened 2023-06-30 04:36 UTC
![image](https://github.com/KENNYSOFT/WzComparerR2/assets/58067113/6d29c59e-9377-4c2b-991e-dbd2dc2e304e)
cant turn object from 'System.Func`2[System.Decimal,System.Decimal]' into type 'System.Iconvertible'

**Comment by PirateIzzy** [comment] 2023-06-30 04:56
The issue is caused by an error Nexon made with the `mpCon` formula for this skill; it's written as "30+d`*`(x/6)" instead of "30+d(x/6)". The incorrect formatting causes the skill tooltip to break.
![image](https://github.com/KENNYSOFT/WzComparerR2/assets/34289651/faaa5958-9946-485d-911a-682ae0c794ac)

**Comment by KENNYSOFT** [comment] 2023-11-05 15:27
Kagamia@adda4ee8886fab405fd8eb722554c28364ba0354

Resolved in 3a780483951d0a2f4edfe4974a0f6f3407e55547

**Closed by KENNYSOFT** 2023-11-05 15:27 UTC
Labels: duplicate
